hydra:
  searchpath:
  - file:///opt/NeMo/examples/nlp/language_modeling/conf

llama_param_size: 1.5B

run:
  name: llama_1.5B_Goldfish_K=10_H=13_GBS=120_EPOCH=83
  results_dir: /store/a06/.NeMo/Goldfish_Llama3/results_dir
trainer:
  num_nodes: 1
  devices: 1
  accelerator: gpu
  precision: bf16
  logger: false
  enable_checkpointing: false
  use_distributed_sampler: false
  max_epochs: null
  max_steps: 1
  max_time: 02:00:00:00
  log_every_n_steps: 10
  val_check_interval: 200
  limit_val_batches: 0
  limit_test_batches: 0
  accumulate_grad_batches: 1
  gradient_clip_val: 1.0
exp_manager:
  explicit_log_dir: /store/swissai/a06/.NeMo/Goldfish_Llama3/${llama_param_size}/${run.name}/results
  exp_dir: null
  name: megatron_llama_3_1_${llama_param_size}
  create_wandb_logger: False
  wandb_logger_kwargs:
    project: nemo_llama_3_1_70b_pretrain
    name: ${run.name}
  resume_if_exists: true
  resume_ignore_no_checkpoint: true
  # resume_from_checkpoint: /store/a06/.NeMo/Goldfish_Llama3/1.5B/llama_1.5B_Goldfish_K_54_H_13_GBS_120_EPOCH_76/results/checkpoints/megatron_llama_3_1_1.5B-step=2100-consumed_samples=252000.0
  create_checkpoint_callback: true
  checkpoint_callback_params:
    async_save: true
    every_n_train_steps: 1 # gradident step
    always_save_nemo: false
    save_nemo_on_train_end: false
    filename: megatron_llama_3_1_${llama_param_size}-{step}-{consumed_samples}
    model_parallel_size: 1
    every_n_epochs: null
    monitor: consumed_samples
    save_top_k: -1
    save_last: False
    save_weights_only: False
  log_step_timing: true
  step_timing_kwargs:
    sync_cuda: true
    buffer_size: 5
  seconds_to_sleep: 60
model:
  mcore_gpt: true
  micro_batch_size: 1
  global_batch_size: 1
  tensor_model_parallel_size: 1
  pipeline_model_parallel_size: 1
  sequence_parallel: false
  context_parallel_size: 1
  encoder_seq_length: 8192
  max_position_embeddings: 8192
  num_layers: 16 # HF num_hidden_layers: 32 -> 16
  hidden_size: 2048 # HF hidden_size: 4096 -> 2048
  ffn_hidden_size: 8192 # HF intermediate_size: 14336 -> 8192
  num_attention_heads: 32 
  num_query_groups: 8
  init_method_std: 0.01 # HF initializer_range: 0.02
  use_scaled_init_method: true
  hidden_dropout: 0.0
  attention_dropout: 0.0
  ffn_dropout: 0.0
  kv_channels: null
  apply_query_key_layer_scaling: true
  normalization: rmsnorm
  layernorm_epsilon: 1.0e-05
  do_layer_norm_weight_decay: false
  make_vocab_size_divisible_by: 128
  pre_process: true
  post_process: true
  persist_layer_norm: true
  bias: false
  activation: fast-swiglu
  headscale: false
  transformer_block_type: pre_ln
  openai_gelu: false
  normalize_attention_scores: true
  position_embedding_type: rope
  rotary_percentage: 1.0
  apply_rope_fusion: true
  cross_entropy_loss_fusion: true
  attention_type: multihead
  share_embeddings_and_output_weights: false # HF tie_word_embeddings: false -> true
  scale_positional_embedding: true
  tokenizer:
    library: huggingface
    type: /capstor/store/cscs/swissai/a06/models/Meta-Llama-3.1-8B # Should I change anything here? The tokenizer is said to be different
    use_fast: true
  native_amp_init_scale: 4294967296
  native_amp_growth_interval: 1000
  hysteresis: 2
  fp32_residual_connection: false
  fp16_lm_cross_entropy: false
  megatron_amp_O2: true
  grad_allreduce_chunk_size_mb: 125
  grad_div_ar_fusion: true
  gradient_accumulation_fusion: true
  bias_activation_fusion: true
  bias_dropout_add_fusion: true
  masked_softmax_fusion: true
  seed: 1234
  use_cpu_initialization: false
  onnx_safe: false
  apex_transformer_log_level: 30
  gradient_as_bucket_view: true
  sync_batch_comm: false
  activations_checkpoint_granularity: null
  activations_checkpoint_method: null
  activations_checkpoint_num_layers: null
  num_micro_batches_with_partial_activation_checkpoints: null
  activations_checkpoint_layers_per_pipeline: null
  deterministic_mode: false
  dist_ckpt_format: torch_dist
  dist_ckpt_load_on_device: true
  dist_ckpt_parallel_save: true
  transformer_engine: true
  fp8: false
  fp8_e4m3: false
  fp8_hybrid: false
  fp8_margin: 0
  fp8_interval: 1
  fp8_amax_history_len: 1024
  fp8_amax_compute_algo: max
  ub_tp_comm_overlap: false
  use_flash_attention: true
  gc_interval: 100
  nsys_profile:
    enabled: false
    trace:
    - nvtx
    - cuda
    start_step: 200
    end_step: 200
    ranks:
    - 0
    gen_shape: true
  optim:
    name: mcore_distributed_optim
    lr: 0.0001
    weight_decay: 0.1
    betas:
    - 0.9
    - 0.95
    bucket_cap_mb: 125
    overlap_grad_sync: true
    overlap_param_sync: true
    contiguous_grad_buffer: true
    contiguous_param_buffer: true
    sched:
      name: CosineAnnealing
      warmup_steps: 500
      constant_steps: 0
      min_lr: 1.0e-05
  data:
    data_impl: mmap
    # splits_string: 900,50,50
    seq_length: 8192
    skip_warmup: true
    num_workers: 2
    num_dataset_builder_threads: 1
    dataloader_type: single
    reset_position_ids: true
    reset_attention_mask: true
    eod_mask_loss: true
    index_mapping_dir: null
    data_prefix: {
      train: [
        /capstor/scratch/cscs/xyixuan/fineweb-edu-80B/finewebedu-llama3tok_text_document,
        /iopsstor/scratch/cscs/xyixuan/dataset/sparse_gutenberg/rep_128/00000_tokens,
        /iopsstor/scratch/cscs/xyixuan/dataset/sparse_gutenberg/rep_256/00000_tokens,
        /iopsstor/scratch/cscs/xyixuan/dataset/sparse_gutenberg/rep_512/00000_tokens,
        /iopsstor/scratch/cscs/xyixuan/dataset/sparse_gutenberg/rep_1024/00000_tokens,
        /iopsstor/scratch/cscs/xyixuan/dataset/sparse_gutenberg/rep_2048/00000_tokens,

      ],
      validation: [
        /iopsstor/scratch/cscs/xyixuan/dataset/sparse_gutenberg/rep_1/00000_tokens,
      ],
      test: [
        /iopsstor/scratch/cscs/xyixuan/dataset/sparse_gutenberg/rep_1/00000_tokens,
      ],
      comment: The training dataset's weights are computed automatically by dividing each data prefix's token count by the total token count across all prefixes. The validation and test dataset paths are placeholders; please substitute them with any minimal tokenized datasets as needed.
    }
    goldfish_loss: true 
    goldfish_k: 4
    goldfish_h: 13
enable_megatron_timers: true
megatron_timer_kwargs:
  log_every_n_steps: 10
  log_mode: minmax
  barrier: false